name: Apply CriticalCSS
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  purgecss:
    runs-on: ubuntu-latest
    steps:
      - name: Install critical
        run: |
          sudo npm i -g critical --unsafe-perm
      - uses: actions/checkout@v2 # This is a premade github action
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Run critical
        run: |
          find . -type f \( -iname "*.htm" -o -iname "*.html" \)|while read fname; do
            sed -i '/<style>.*<\/style>$/d' "$fname"
            critical "$fname" --base . --inline --css assets/css/*.css > "$fname"-crit
            mv "$fname"-crit "$fname"
          done
        #run: critical index.html --base . --inline --css assets/css/*.css
      - name: Commit files
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "applied criticalcss to all HTML files"
      - name: Push changes
        uses: ad-m/github-push-action@master # This is a premade github action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
