name: Remove unused External CSS code
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "5 0 * * *" # Every day at 00:05 UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  purgecss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # This is a premade github action
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Install purgecss # https://purgecss.com/CLI.html#safelist also using sudo with purgecss to get beter results (?)
        run: |
          sudo npm i -g purgecss
          sudo purgecss --css ../**/*.css --content "**.html" "**.js" --output assets/css/
      - name: Commit files
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "purged CSS files"
      - name: Push changes
        uses: ad-m/github-push-action@master # This is a premade github action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
