name: Remove unused & make critical css
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "5 0 * * *" # Every day at 00:05 UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  purgecss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # This is a premade github action
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Install purgecss # https://purgecss.com/CLI.html#safelist also using sudo with purgecss to get beter results (?)
        run: |
          sudo npm i -g purgecss
      - name: Install critical
        run: |
          sudo npm i -g critical --unsafe-perm
      - name: Run purgecss
        run: |
          sudo purgecss --css ../**/*.css --content "**.html" "**.js" --output assets/css/
      - name: Run critical
        run: | # Find each HTML file on root. remove online (critical)css. Add critical css to temp html file. Rename temp html file to original.
          find . -type f \( -iname "*.htm" -o -iname "*.html" \)|while read fname; do
            sed -i '/<style>.*<\/style>$/d' "$fname"
            critical "$fname" --base . --inline --css assets/css/*.css > "$fname"-crit
            mv "$fname"-crit "$fname"
          done
      - name: Commit files
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "purged & made critical CSS"
      - name: Push changes
        uses: ad-m/github-push-action@master # This is a premade github action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
  lighthouse:
    needs: purgecss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm 404.html
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          budgetPath: '.github/.lighthouse/budget.json' # test performance budgets
          configPath: '.github/.lighthouse/lighthouserc.json'
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
